### ISSUE TITLE
order of fields is randomised

### ISSUE THREAD

**Issue by joetym** [nichtich/Text-MarkdownTable#8]
The fields I'm passing into this are coming out in a random order, whereas I would like to specify the order. I'm guessing this is because hash order isn't guaranteed in Perl. This is even if pass in the columns explicitly.

What what would be useful either/or:
 - accept an ARRAYREF rather than a HASHREF when adding values to the table
 - have some correlation between columns and the values added (the fields still come out in random order if specify column names that correlate to the keys of the HASHREF containing the field values)

**Comment by joetym** [comment]
From further experimentation the order is specified by the keys alphabetically, which works. But doesn't make the most readable code.

**Comment by nichtich** [comment]
Option `columns` is only for column *names*. Order of hashref fields can be specified with `fields`.

**Comment by joetym** [comment]
Thanks, that makes sense. It might be an idea to add an example to the synopsis as I completely overlooked it in the docs, probably a common mistake.

Thanks again.
